name: Feature request
description: Propose a change in capability
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: What are you unable to do today? Describe the situation, not the solution.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: What you have tried or considered
    validations:
      required: false
